# The base image used for all images that require a MITIE model
FROM debian:bookworm

RUN apt-get update && apt-get install -y bzip2 make wget

# download mitie model
WORKDIR /build
COPY ./Makefile .
RUN make prepare-mitie
