services:
  app:
    image: wmw/rasa:localdev-full
    environment:
      DB_DRIVER: "postgresql"
      DB_USER: "admin"
      DB_PASSWORD: "postgres"

    ports:
    - "5005:5005"
    volumes:
      - ../ha:/app

    command: run --enable-api -m /app/models --endpoints /app/endpoints.yml --connector rest

  action-server:
    image: wmw/rasa:localdev
    ports:
    - "5055:5055"
    volumes:
      - ../ha:/app

    command: run actions

  db:
    image: "bitnami/postgresql:17"
    restart: unless-stopped
    volumes:
      - postgres-data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_DATABASE: rasa
      POSTGRESQL_PASSWORD: postgres

  duckling:
    restart: unless-stopped
    image: "rasa/duckling:0.2.0.2"
    expose:
      - "8000"
    command: ["duckling-example-exe", "--no-access-log", "--no-error-log"]

  redis:
    restart: unless-stopped
    image: "bitnami/redis:7.4"
    environment:
      REDIS_PASSWORD: "redis"
    expose:
      - "6379"

volumes:
  postgres-data: null
