services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/python:3.10-bookworm
    environment:
      DB_DRIVER: "postgresql"
      DB_USER: "admin"
      DB_PASSWORD: "postgres"

    volumes:
      - ..:/workspaces/rasa:cached
      - ~/.cache/vscode:/home/vscode/.cache

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while true; sleep 1; done"

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

  db:
    image: "bitnami/postgresql:11"
    restart: unless-stopped
    volumes:
      - postgres-data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_DATABASE: rasa
      POSTGRESQL_PASSWORD: postgres

  duckling:
    restart: unless-stopped
    image: "rasa/duckling:0.2.0.2"
    expose:
      - "8000"
    command: ["duckling-example-exe", "--no-access-log", "--no-error-log"]

  redis:
    restart: unless-stopped
    image: "bitnami/redis:6.2"
    environment:
      REDIS_PASSWORD: "redis"
    expose:
      - "6379"

volumes:
  postgres-data: null
